name: hCash
description: Cash
version: 1.0
softdepend: [Vault]
author: zHonra_
main: com.hero.moedaplugin.Main
commands:
  cash:
    usage: /<command> 
    description: Comando para o cash
    aliases: [cash]
  npc:
    description: command
    aliases: [aliases,as,alis]
  shop:
    description: Command of shop
    aliases: [aliases,as,alis]
  vip:
    usage: /<command>
    description: Command of shopvip
    aliases: [aliases,as,alis]